version: '3'

services:
  server:
      build: .
      ports:
        - "8000:8000"  
      volumes:
        - ./server/testTaskServer:/app/testTaskServer 
      networks:
        - app-network
      environment:
        - DATABASE_URL=mysql://root:root@db:3306/dzencode_db  
        - REDIS_URL=redis://redis:6379 
        - PORT=8000

  # client: Ждёмс пока пофиксят баг с npm'ом :( 
  #     build: ./client  
  #     ports:
  #       - "5173:5173" 
  #     volumes:
  #       - ./client:/app  
  #     networks:
  #       - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dzencode_db
    ports:
      - "3307:3306" 
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379" 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge